/**
 * AI Telemetry Fallback - Phase 2
 */

export const AIEventType = {
  SERVICE_ACCESSED: 'SERVICE_ACCESSED',
  SYSTEM_STATUS: 'SYSTEM_STATUS',
  EMERGENCY_SHUTDOWN: 'EMERGENCY_SHUTDOWN',
  ADAPTIVE_SUGGESTION_CLICKED: 'ADAPTIVE_SUGGESTION_CLICKED',
  INSIGHTS_DELIVERED: 'INSIGHTS_DELIVERED',
  ONBOARDING_COMPLETED: 'ONBOARDING_COMPLETED',
  PATTERN_CACHE_HIT: 'PATTERN_CACHE_HIT',
  PATTERN_CACHE_MISS: 'PATTERN_CACHE_MISS',
  PATTERN_CACHE_SAVED: 'PATTERN_CACHE_SAVED',
  PATTERN_CACHE_INVALIDATED: 'PATTERN_CACHE_INVALIDATED',
  INSIGHTS_REQUESTED: 'INSIGHTS_REQUESTED',
  UNIFIED_PIPELINE_COMPLETED: 'UNIFIED_PIPELINE_COMPLETED',
  UNIFIED_PIPELINE_ERROR: 'UNIFIED_PIPELINE_ERROR',
  DELETE_QUEUED_OFFLINE: 'DELETE_QUEUED_OFFLINE',
} as const;

export const trackAIInteraction = async (eventType: any, data?: any, userId?: string) => {
  // AI telemetry disabled - support 1-3 params
  if (__DEV__) {
    console.log(`🚫 AI Telemetry disabled: ${eventType}`, data, userId);
  }
};
