#!/bin/bash

# 🧹 Test Invalid Entries Cleanup System
# This script provides Metro console commands to test and fix invalid mood entries

echo "🧹 ====================================="
echo "🧹 INVALID ENTRIES CLEANUP TEST GUIDE"
echo "🧹 ====================================="
echo ""
echo "📱 1. Start Metro console and wait for app to load"
echo ""
echo "🔍 2. SCAN for invalid entries:"
echo "   debugInvalidEntries.scan()"
echo "   debugInvalidEntries.scan('YOUR_USER_ID')"  # For specific user
echo ""
echo "📊 3. GET integrity report:"
echo "   debugInvalidEntries.report()"
echo "   debugInvalidEntries.report('YOUR_USER_ID')"  # User-specific
echo ""
echo "🧪 4. DRY RUN cleanup (safe):"
echo "   debugInvalidEntries.cleanup('YOUR_USER_ID', true)"
echo ""
echo "🔥 5. ACTUAL cleanup (removes data!):"
echo "   debugInvalidEntries.cleanup('YOUR_USER_ID', false)"
echo ""
echo "🔄 6. TEST auto-recovery (with new validation):"
echo "   debugInvalidEntries.testRecovery('YOUR_USER_ID')"
echo ""
echo "💡 EXAMPLE WORKFLOW:"
echo "   1. debugInvalidEntries.scan()                      # See all issues"
echo "   2. debugInvalidEntries.report('d4caa77e-...')      # User-specific report"
echo "   3. debugInvalidEntries.cleanup('d4caa77e-...', true) # Dry run"
echo "   4. debugInvalidEntries.cleanup('d4caa77e-...', false) # Real cleanup"
echo "   5. debugInvalidEntries.testRecovery('d4caa77e-...')   # Test recovery"
echo ""
echo "⚠️ NOTES:"
echo "   - Always run DRY RUN first"
echo "   - Replace 'YOUR_USER_ID' with actual user ID"
echo "   - Cleanup permanently removes invalid entries"
echo "   - Recovery test should show '0 invalid entries' after cleanup"
echo ""
echo "🚨 EXPECTED RESULTS:"
echo "   - Before: 267 invalid entries found"
echo "   - Cleanup: 267 invalid entries removed"
echo "   - After: 0 invalid entries, clean sync queue"
