#!/bin/bash

# 🔍 Advanced Mood Deletion Debug Guide v2
# Deep investigation tools for persistent deletion issues

echo "🔍 ======================================="
echo "🔍 ADVANCED MOOD DELETION DEBUG GUIDE v2"
echo "🔍 ======================================="
echo ""
echo "📱 1. Start Metro console and wait for app to load"
echo ""
echo "🕵️ 2. DEEP SCAN a specific mood entry:"
echo "   debugMoodDeletionV2.deepScan('MOOD_ENTRY_ID', 'YOUR_USER_ID')"
echo "   # This will show WHERE the entry exists (local v1/v2, remote, cache)"
echo ""
echo "🔥 3. AGGRESSIVE DELETE (removes from ALL locations):"
echo "   debugMoodDeletionV2.aggressiveDelete('MOOD_ENTRY_ID', 'YOUR_USER_ID')"
echo "   # This removes from local, remote, and all caches"
echo ""
echo "🧪 4. TEST deletion resilience:"
echo "   debugMoodDeletionV2.testResilience('YOUR_USER_ID')"
echo "   # Creates test entry, deletes it, verifies it's gone"
echo ""
echo "💥 5. NUCLEAR OPTION (DELETE ALL mood data - USE WITH CAUTION!):"
echo "   debugMoodDeletionV2.nuclearCleanup('YOUR_USER_ID', true)"
echo "   # ⚠️ This permanently deletes ALL mood data for the user!"
echo ""
echo "💡 TYPICAL WORKFLOW FOR DEBUGGING:"
echo ""
echo "1️⃣ First, identify the problematic entry ID from logs"
echo "2️⃣ Run deep scan to see where it exists:"
echo "   debugMoodDeletionV2.deepScan('mood_5b49e859-c237-4837-9bbb-47cf67e4e7c8', 'd4caa77e-c762-4617-9c28-25390a26d7b6')"
echo ""
echo "3️⃣ Try aggressive delete:"
echo "   debugMoodDeletionV2.aggressiveDelete('mood_5b49e859-c237-4837-9bbb-47cf67e4e7c8', 'd4caa77e-c762-4617-9c28-25390a26d7b6')"
echo ""
echo "4️⃣ Test if deletion is working properly:"
echo "   debugMoodDeletionV2.testResilience('d4caa77e-c762-4617-9c28-25390a26d7b6')"
echo ""
echo "🔍 WHAT TO LOOK FOR:"
echo "   - Found in local: true/false (v1 plain vs v2 encrypted)"
echo "   - Found in remote: true/false (Supabase)"
echo "   - Found in cache: true/false (IntelligentMerge cache)"
echo "   - Multiple versions in different storage keys"
echo ""
echo "⚠️ COMMON ISSUES:"
echo "   - Entry exists in both v1 and v2 formats"
echo "   - IntelligentMerge cache has stale data"
echo "   - V1→V2 migration resurrects deleted entries"
echo "   - Remote has entry but local deletion doesn't sync"
echo ""
echo "🚨 IF ALL ELSE FAILS:"
echo "   debugMoodDeletionV2.nuclearCleanup('YOUR_USER_ID', true)"
echo "   # ⚠️ This will delete EVERYTHING - only use as last resort!"
