#!/bin/bash

echo "🗑️ MOOD DELETION DEBUG TEST GUIDE"
echo "=================================="
echo ""
echo "This script provides commands to test mood deletion functionality."
echo "Run these commands in Metro console (expo start) to debug deletion issues."
echo ""
echo "Prerequisites:"
echo "1. Start your app with: expo start"
echo "2. Open Metro console in browser"
echo "3. Navigate to mood screen and add some test entries first"
echo ""
echo "STEP 1: List current mood entries and storage"
echo "============================================="
echo "debugMoodDeletion.scanStorage('YOUR_USER_ID')"
echo ""
echo "STEP 2: Test deletion of a specific entry"
echo "=========================================="
echo "// Replace ENTRY_ID with actual mood entry ID"
echo "debugMoodDeletion.testDeletion('YOUR_USER_ID', 'ENTRY_ID')"
echo ""
echo "STEP 2B: Test FORCE deletion (if standard deletion fails)"
echo "========================================================"
echo "debugMoodDeletion.testForceDeletion('YOUR_USER_ID', 'ENTRY_ID')"
echo ""
echo "STEP 3: Check if deletion worked"
echo "==============================="
echo "debugMoodDeletion.scanStorage('YOUR_USER_ID')"
echo ""
echo "EMERGENCY: Clean all mood storage (BE CAREFUL!)"
echo "==============================================="
echo "debugMoodDeletion.cleanStorage()"
echo ""
echo "🔍 WHAT TO LOOK FOR:"
echo "- Entry should be removed from all storage keys"
echo "- testDeletion should return success: true"
echo "- Entry count should decrease after deletion"
echo "- Entry should not reappear after page refresh"
echo ""
echo "🚨 IF DELETION STILL FAILS:"
echo "1. Check the enhanced debug logs in console"
echo "2. Look for encryption/decryption errors"
echo "3. Check if entry exists in multiple storage locations"
echo "4. Verify the entry ID format (UUID vs local ID)"
echo ""
echo "Debugging with live app:"
echo "1. Go to mood screen"
echo "2. Try deleting an entry"
echo "3. Watch console logs for detailed deletion process"
echo "4. Check if entry reappears after pull-to-refresh"
